import { Job } from "./types";

function job(
  id: number,
  title: string,
  company: string,
  location: string,
  remote: boolean,
  url: string,
  category: string,
  matchScore: number,
  applyTier: "full-auto" | "one-click" | "guided",
  description: string,
  requirements: string[],
  whyYou: string[],
  coverLetter: string,
  salary?: string,
): Job {
  return {
    id: `seed-${String(id).padStart(3, "0")}`,
    title,
    company,
    location,
    remote,
    salary,
    url,
    source: "seed",
    category,
    description,
    requirements,
    matchScore,
    whyYou,
    applyTier,
    status: "new",
    generatedMaterials: {
      coverLetter,
      bioVariantUsed: "creative-technologist",
      resumePresetUsed: "default",
      customAnswers: [],
    },
  };
}

export const SEED_JOBS: Job[] = [
  // ─── FELLOWSHIPS ───────────────────────────────────────────────
  job(1, "Google Creative Fellowship - Copywriter Track", "Google", "Mountain View, CA", false,
    "https://creativefellowship.google", "fellowship", 85, "one-click",
    "A fellowship for emerging creative copywriters to work alongside Google's brand and marketing teams, developing campaigns across Google products.",
    ["Strong portfolio of creative writing", "Interest in technology and brand storytelling", "BA/BS required"],
    ["Playwright and producer with a distinctive creative voice honed at Edinburgh Fringe and Juilliard", "Founder of HZL Studio -- you build with AI, not just write about it", "Fordham BA with bilingual English/German range"],
    "I'm a playwright who builds AI systems, applying for the Copywriter track. My work spans Edinburgh Fringe productions, Juilliard training, and founding HZL Studio where I ship AI-powered education tools. I write with precision because I build with precision -- every line of copy I produce is informed by technical fluency and theatrical instinct. I'd bring Google a voice that's both creatively bold and technically grounded."),

  job(2, "Google Creative Fellowship - Social Creative Track", "Google", "Mountain View, CA", false,
    "https://creativefellowship.google", "fellowship", 82, "one-click",
    "A fellowship for social-first creatives to shape Google's voice across platforms, creating content that connects with diverse audiences.",
    ["Social media portfolio", "Understanding of platform-specific content", "Creative storytelling ability"],
    ["Theatre background gives you an instinct for audience engagement and timing", "Experience building communities around creative projects and tech products", "Young, digitally native voice with cross-cultural perspective (German fluency, international work)"],
    "I'm a 22-year-old playwright and technologist applying for the Social Creative track. I've built audiences for Edinburgh Fringe shows and AI products alike, and I understand how to make complex ideas land in a scroll. My theatre training taught me to read a room; my tech work taught me to read analytics. I'd bring both to Google's social presence."),

  job(3, "NYT AI Initiatives Fellow", "The New York Times", "New York, NY", false,
    "https://job-boards.greenhouse.io/thenewyorktimes/jobs/4618264005", "fellowship", 80, "one-click",
    "Fellowship exploring how AI can enhance journalism, editorial workflows, and reader experiences at The New York Times.",
    ["Interest in AI and journalism", "Strong writing skills", "Technical curiosity"],
    ["Founder of HZL Studio -- you've shipped real AI products, not just theorized about them", "Professional writer with theatre credits and editorial instinct", "Fordham education with deep humanistic grounding in how AI intersects with culture"],
    "I build AI systems and I write professionally -- that intersection is exactly what this fellowship explores. As founder of HZL Studio, I've designed AI-powered education tools from scratch. As a playwright, I understand narrative, audience, and editorial craft. I'd bring the Times a technologist who thinks like a writer and a writer who ships like an engineer."),

  job(4, "Anthropic AI Safety Fellow", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5023394008", "fellowship", 78, "one-click",
    "Fellowship focused on AI safety research, policy, and alignment. Work with Anthropic's safety teams on frontier challenges.",
    ["Interest in AI safety and alignment", "Strong analytical and writing skills", "Technical background preferred"],
    ["You build AI products (HZL Studio) and think deeply about responsible deployment", "Interdisciplinary thinker -- theatre, tech, and ethics converge in your work", "Young founder perspective on how AI actually gets used by real people"],
    "I'm a founder who builds AI education tools and a writer who thinks critically about what AI means for people. At HZL Studio, safety isn't theoretical -- I make decisions daily about how AI interacts with students. I'd bring Anthropic a practitioner's perspective on alignment: someone who ships AI and cares deeply about getting it right."),

  // ─── AI / SAFETY ───────────────────────────────────────────────
  job(5, "AI Red Teamer Entry Level", "10a Labs", "Remote", true,
    "https://job-boards.greenhouse.io/10alabs/jobs/4002004009", "ai-safety", 75, "one-click",
    "Entry-level AI red teaming role focused on testing and evaluating AI systems for safety vulnerabilities and failure modes.",
    ["Familiarity with AI/ML systems", "Creative problem-solving", "Strong written communication"],
    ["You build AI systems and know where they break -- founder-level understanding of failure modes", "Creative writer trained to think from multiple perspectives (theatre background)", "Technical enough to probe systems, articulate enough to document findings"],
    "I build AI systems and I break them. As founder of HZL Studio, I test my own AI tools relentlessly -- I know how language models fail because I ship products that depend on them working. My theatre training taught me to inhabit different perspectives, which is exactly what red teaming requires. I'd bring 10a Labs a tester who thinks like a builder."),

  job(6, "Creative Technologist", "Wonder Studios", "New York, NY", false,
    "https://job-boards.eu.greenhouse.io/wonderstudios/jobs/4750752101", "ai-safety", 72, "one-click",
    "Creative technologist role bridging AI tools and visual storytelling at Wonder Studios' NYC office.",
    ["Experience with AI/ML tools", "Creative portfolio", "Collaborative mindset"],
    ["Playwright and technologist -- you literally bridge creative and technical worlds", "NYC-based with production experience (Edinburgh Fringe, Juilliard)", "Founder of an AI studio; you ship creative technology"],
    "I'm a playwright who codes and a coder who produces theatre -- Creative Technologist isn't just a title for me, it's what I do. I founded HZL Studio to build AI-powered education tools, and I've produced work at Edinburgh Fringe and trained at Juilliard. I'd bring Wonder Studios someone who lives at the intersection of art and technology."),

  job(7, "AI Engineer", "EvolutionIQ", "Remote", true,
    "https://www.evolutioniq.com/careers", "ai-safety", 45, "guided",
    "AI engineering role building machine learning systems for insurance claims automation.",
    ["3+ years ML engineering", "Python, PyTorch/TensorFlow", "Production ML systems experience"],
    ["Self-taught builder who ships AI products at HZL Studio", "Strong Python and systems thinking from building full-stack AI tools", "Fast learner with founder-level breadth across the ML stack"],
    "I'm a self-taught AI builder and founder of HZL Studio, where I design and ship AI-powered tools. While my background is non-traditional, I bring the resourcefulness of someone who's built production AI systems from scratch. I learn fast and build faster."),

  job(8, "Senior AI Engineer", "Conversica", "Remote", true,
    "https://www.conversica.com/careers", "ai-safety", 40, "guided",
    "Senior AI engineering role working on conversational AI systems for enterprise sales and marketing.",
    ["5+ years AI/ML experience", "NLP expertise", "Production systems at scale"],
    ["Experience building conversational AI tools at HZL Studio", "Deep understanding of language from both technical and creative perspectives", "Founder who's shipped AI products end-to-end"],
    "As founder of HZL Studio, I've built conversational AI tools from the ground up. My playwright's ear for dialogue informs how I think about conversational AI -- I care about how machines talk to people. I'd bring Conversica a builder's perspective on making AI conversations feel human."),

  job(9, "Junior SWE AI Native Pod", "OakNorth", "Remote", true,
    "https://www.oaknorth.com/careers", "ai-safety", 55, "guided",
    "Junior software engineer role in OakNorth's AI-native development pod, building with AI tools from day one.",
    ["CS degree or equivalent experience", "Familiarity with AI development tools", "Strong fundamentals"],
    ["AI-native builder -- you use AI tools to build AI tools at HZL Studio", "Fordham BA with self-taught engineering skills", "Young founder comfortable working at the frontier of AI-assisted development"],
    "I'm an AI-native builder. At HZL Studio, I use AI tools to build AI products -- it's how I work, not just what I work on. I'd bring OakNorth a junior engineer who already thinks in the AI-native paradigm you're building around."),

  job(10, "AI Systems Engineer", "Launch Labs", "Remote", true,
    "https://www.launchlabs.ai/careers", "ai-safety", 50, "guided",
    "AI systems engineering role building infrastructure for AI product deployment and monitoring.",
    ["Systems engineering background", "AI/ML deployment experience", "Infrastructure knowledge"],
    ["Founder who's deployed AI systems in production at HZL Studio", "Full-stack understanding from frontend to model serving", "Self-taught systems thinker with strong fundamentals"],
    "I've deployed AI systems in production as founder of HZL Studio, handling everything from model integration to user-facing interfaces. I understand the full stack because I've built it myself. I'd bring Launch Labs a systems engineer with a founder's sense of urgency."),

  job(11, "Frontend Engineer Entry Level", "Truveta", "Remote", true,
    "https://www.truveta.com/careers", "ai-safety", 52, "guided",
    "Entry-level frontend engineering role building data visualization and health AI interfaces.",
    ["React/TypeScript experience", "Interest in healthcare/AI", "Strong UI sensibilities"],
    ["Full-stack builder at HZL Studio with strong React/Next.js skills", "Design sensibility from theatre and production background", "Passionate about using technology to improve lives"],
    "I build frontend interfaces for AI-powered education tools at HZL Studio using React, Next.js, and TypeScript. My theatre background gives me an unusual sensitivity to user experience -- I think about how interfaces feel, not just how they function. I'd bring Truveta a frontend engineer with both technical skills and design instinct."),

  // ─── COPYWRITING ───────────────────────────────────────────────
  job(12, "Junior Creative Copywriter", "UnitedMasters", "New York, NY", false,
    "https://www.unitedmasters.com/careers", "copywriting", 70, "guided",
    "Junior copywriter creating brand and marketing copy for UnitedMasters' artist-first music distribution platform.",
    ["1-2 years copywriting experience", "Interest in music/culture", "Portfolio required"],
    ["Professional writer with credits at Edinburgh Fringe and Juilliard training", "Deep connection to culture, music, and the creator economy", "NYC-based with a voice that's bold, young, and culturally fluent"],
    "I'm a playwright with Edinburgh Fringe credits and Juilliard training applying to write for artists. My creative voice is theatrical, direct, and culturally attuned -- exactly what UnitedMasters' brand demands. I understand creators because I am one, and I'd bring your copy the authenticity of someone who lives in the culture."),

  job(13, "Junior Copywriter", "Gruns", "Remote", true,
    "https://www.gruns.com/careers", "copywriting", 68, "one-click",
    "Junior copywriter crafting product and brand copy for a health-focused food brand.",
    ["Strong writing samples", "Interest in health/wellness", "Attention to detail"],
    ["Trained writer with professional theatre credits", "Versatile voice -- can write everything from dramatic monologues to product descriptions", "Detail-oriented with a playwright's precision for word choice"],
    "I'm a professional writer applying my craft to brand copy. My training is in playwriting -- Edinburgh Fringe, Juilliard -- which means I obsess over every word. I'd bring Gruns copy that's precise, engaging, and crafted with a writer's ear for how language lands."),

  job(14, "Junior Copywriter", "Grove Collaborative", "Remote", true,
    "https://www.grove.co/careers", "copywriting", 65, "guided",
    "Junior copywriter for Grove Collaborative's sustainability-focused home essentials brand.",
    ["Writing samples required", "Interest in sustainability", "Brand voice adaptability"],
    ["Professional writer with range from theatre to tech", "Passionate about mission-driven brands", "Young, fresh voice with sophisticated craft"],
    "I write professionally across theatre, tech, and brand contexts. As a playwright, I know how to give a brand a voice that feels human and intentional. I'd bring Grove a writer who cares about the mission and has the craft to communicate it beautifully."),

  job(15, "Graduate/Associate Copywriter", "Canonical", "Remote", true,
    "https://canonical.com/careers", "copywriting", 63, "one-click",
    "Graduate copywriter role creating technical and brand content for Canonical, the company behind Ubuntu.",
    ["Recent graduate", "Technical writing ability", "Interest in open source"],
    ["Fordham BA with strong writing foundation", "Technical fluency from building AI systems at HZL Studio", "Ability to make complex technical concepts accessible and engaging"],
    "I'm a Fordham graduate who writes professionally and builds AI systems. That combination -- technical fluency plus editorial craft -- is what technical copywriting demands. I'd bring Canonical a writer who understands your technology and can explain it with clarity and style."),

  job(16, "Junior Copywriter", "NPHub", "Remote", true,
    "https://jobs.lever.co/nphub/46925f47-ddd9-43ad-81a7-fbc92c5647e4", "copywriting", 65, "one-click",
    "Junior copywriter creating marketing and brand content for NPHub's publishing platform.",
    ["Strong writing portfolio", "Marketing awareness", "Creative thinking"],
    ["Professional writer with credits spanning theatre, tech, and editorial", "Creative thinker trained at Juilliard and Edinburgh Fringe", "Young voice with professional polish"],
    "I'm a professional writer with theatre credits and AI experience applying to craft your brand copy. My training at Juilliard and Edinburgh Fringe gave me a voice that's both bold and precise. I'd bring NPHub a copywriter who thinks creatively and writes with professional discipline."),

  job(17, "Marketing Copywriter", "StackAdapt", "Remote", true,
    "https://job-boards.greenhouse.io/stackadapt/jobs/4113958009", "copywriting", 60, "one-click",
    "Marketing copywriter creating campaign content, landing pages, and ad copy for a programmatic advertising platform.",
    ["2+ years copywriting", "B2B marketing experience preferred", "Data-driven mindset"],
    ["Professional writer who also understands data and technology", "Experience building and marketing AI products at HZL Studio", "Versatile voice that can adapt from creative to technical"],
    "I write and I build technology -- that dual fluency makes me an effective marketing copywriter for a tech platform. At HZL Studio I write copy that sells AI products, and my theatre training ensures every word earns its place. I'd bring StackAdapt a writer who understands both the creative and the technical side."),

  job(18, "Copywriter", "DEPT", "Remote", true,
    "https://job-boards.greenhouse.io/dept/jobs/7594669", "copywriting", 58, "one-click",
    "Copywriter creating integrated campaign content across digital channels for DEPT's global agency clients.",
    ["Agency experience preferred", "Portfolio of digital campaigns", "Collaborative spirit"],
    ["Creative writer with Edinburgh Fringe production experience", "Comfortable across formats -- from scripts to social to long-form", "Young, culturally fluent voice with international perspective (German fluency)"],
    "I've produced work at Edinburgh Fringe and built AI products -- I know how to create across formats and contexts. My theatre training makes me a sharp collaborator, and my tech background means I understand digital-first thinking. I'd bring DEPT a copywriter who's both creatively bold and digitally fluent."),

  job(19, "Technical Copywriter (Contract)", "DEPT x Snap", "Remote", true,
    "https://job-boards.greenhouse.io/dept/jobs/7461964", "copywriting", 55, "one-click",
    "Contract technical copywriter creating developer-facing content for Snap's AR platform through DEPT agency.",
    ["Technical writing experience", "Developer documentation skills", "Understanding of AR/XR"],
    ["Technical writer who builds AI systems -- you speak developer fluently", "Strong editorial craft from professional writing background", "Experience translating complex technology into accessible content at HZL Studio"],
    "I build AI systems and write about technology with a professional writer's craft. This combination -- technical depth plus editorial precision -- is what developer-facing content demands. I'd bring clear, engaging technical writing informed by real engineering experience."),

  job(20, "Brand Creative Copywriter", "CloudWalk", "Remote", true,
    "https://jobs.lever.co/cloudwalk/7f4b63e3-2c0d-4c76-98ba-0d04b88f95b8", "copywriting", 55, "one-click",
    "Brand copywriter crafting the creative voice for CloudWalk's fintech platform across all brand touchpoints.",
    ["Creative writing portfolio", "Brand voice development experience", "Fintech interest"],
    ["Professional writer trained at Juilliard with a strong creative voice", "Experience developing brand voices for tech products at HZL Studio", "Bold, distinctive writing style that stands out"],
    "I develop voices for a living -- on stage, in AI products, and in brand copy. My Juilliard training and Edinburgh Fringe credits gave me a writer's voice that's distinctive and intentional. I'd bring CloudWalk a brand copywriter who can craft a fintech voice that feels human, bold, and trustworthy."),

  job(21, "Content Writer & Strategist", "Teramind", "Remote", true,
    "https://www.teramind.co/careers", "copywriting", 58, "guided",
    "Content writer and strategist creating thought leadership, blog posts, and marketing content for an employee monitoring platform.",
    ["Content strategy experience", "SEO awareness", "B2B writing samples"],
    ["Strategic thinker who builds products and writes content at HZL Studio", "Strong analytical mind paired with professional writing craft", "Experience creating content that drives engagement across platforms"],
    "I write and I strategize. At HZL Studio, I create content that serves both users and business goals. My writing is informed by a playwright's discipline and a founder's understanding of what content actually needs to accomplish. I'd bring Teramind a strategist who writes with purpose."),

  job(22, "AI Content Writer", "Jobgether", "Remote", true,
    "https://www.jobgether.com/careers", "copywriting", 60, "guided",
    "AI content writer creating articles, guides, and marketing materials about AI and the future of work.",
    ["Strong writing skills", "AI/tech knowledge", "Content marketing experience"],
    ["You build AI systems and write about them -- authentic AI content expertise", "Professional writer with editorial craft and technical depth", "Young voice at the intersection of AI and culture"],
    "I build AI systems and I write about AI -- not as a journalist, but as a practitioner. At HZL Studio, I design AI-powered education tools, so my content comes from real experience, not research summaries. I'd bring Jobgether an AI content writer whose authority comes from actually building the technology."),

  job(23, "Writing Specialist (Creative Writing)", "xAI", "San Francisco, CA", false,
    "https://xai.com/careers", "copywriting", 65, "guided",
    "Creative writing specialist helping shape the voice and creative output of xAI's AI systems.",
    ["Professional creative writing background", "Understanding of AI/LLMs", "Portfolio required"],
    ["Professional playwright with Edinburgh Fringe and Juilliard credentials", "Founder who builds with LLMs daily at HZL Studio", "Unique intersection of literary craft and AI systems expertise"],
    "I'm a professional playwright who builds with LLMs. My Edinburgh Fringe credits and Juilliard training give me the literary craft; my work at HZL Studio gives me the AI systems expertise. I understand how language models generate text because I build products that depend on it. I'd bring xAI a writing specialist who knows both sides -- the art and the architecture."),

  // ─── COMMUNITY / SOCIAL ────────────────────────────────────────
  job(24, "Social Media Specialist", "Mistral AI", "Remote", true,
    "https://jobs.lever.co/mistral/97a9b891-7979-4ca7-a2d9-f1f5e9107ce5", "community", 72, "one-click",
    "Social media specialist managing Mistral AI's presence across platforms, creating content that makes frontier AI accessible.",
    ["Social media management experience", "Interest in AI", "Strong creative voice"],
    ["You build AI products and can speak authentically about frontier technology", "Creative writer with a young, engaging voice perfect for social", "Bilingual (English/German) with international cultural fluency"],
    "I build AI products and I know how to talk about them. At HZL Studio, I've shaped the voice of an AI education platform; as a playwright, I know how to engage an audience. I'd bring Mistral a social media specialist who can make frontier AI feel accessible without dumbing it down."),

  job(25, "AI Creative Manager", "Vocal Media", "Remote", true,
    "https://jobs.lever.co/get-vocal-pbc/5ef2dc1b-a844-4fe1-98c4-77da252332a5", "community", 65, "one-click",
    "Manage creative AI initiatives at Vocal Media's creator platform, bridging technology and creative communities.",
    ["Creative project management", "AI/tech familiarity", "Community engagement experience"],
    ["Founder of an AI creative studio -- you manage AI creative initiatives daily", "Theatre producer with project management skills from Edinburgh Fringe", "Deep understanding of creator communities and creative workflows"],
    "I manage AI creative initiatives as my day job. At HZL Studio, I lead the development of AI-powered creative tools, and as a theatre producer, I've managed complex creative projects from concept to premiere. I'd bring Vocal Media a creative manager who understands both AI and the creators who use it."),

  job(26, "Digital Community Manager", "Vocal Media", "Remote", true,
    "https://jobs.lever.co/get-vocal-pbc/fb3394a4-354c-4c28-872a-fbdcb02882e8", "community", 62, "one-click",
    "Manage and grow Vocal Media's digital creator community, fostering engagement and supporting content creators.",
    ["Community management experience", "Strong communication skills", "Content creation ability"],
    ["Experience building communities around creative projects and tech products", "Strong communicator with theatre training", "Creator yourself -- you understand community members' needs firsthand"],
    "I build communities around creative work. As a theatre producer and tech founder, I've grown engaged audiences for both artistic and technical projects. I understand creators because I am one, and I'd bring Vocal Media a community manager who genuinely cares about helping creators succeed."),

  job(27, "Junior Creator Program Coordinator", "Vocal Media", "Remote", true,
    "https://jobs.lever.co/get-vocal-pbc/b7205a23-75f9-46c8-8552-5db061b3f16e", "community", 63, "one-click",
    "Coordinate Vocal Media's creator programs, managing partnerships and supporting emerging content creators.",
    ["Program coordination experience", "Interest in creator economy", "Organizational skills"],
    ["Producer who coordinates complex creative programs (Edinburgh Fringe)", "Founder with program management experience at HZL Studio", "Young creative who understands the creator economy from the inside"],
    "I coordinate creative programs -- it's what producing theatre teaches you. My Edinburgh Fringe experience and HZL Studio work have given me the organizational skills and creative sensibility this role requires. I'd bring Vocal Media a coordinator who understands creators and can manage programs with precision."),

  job(28, "Social Media Coordinator", "Huckleberry Labs", "Remote", true,
    "https://www.huckleberrylabs.com/careers", "community", 60, "guided",
    "Social media coordinator managing content calendars and community engagement across platforms.",
    ["Social media experience", "Content creation skills", "Organizational ability"],
    ["Creative writer with strong social media instincts", "Organized producer with project management skills", "Young, digitally native voice with cultural fluency"],
    "I create content and manage projects with a producer's organizational precision. My creative writing background ensures every post has craft, and my tech fluency means I can engage authentically with digital-native audiences. I'd bring Huckleberry Labs a coordinator who's both creative and organized.",
    "$20-29/hr"),

  job(29, "Social Media Coordinator", "Northbeam", "Remote", true,
    "https://www.northbeam.io/careers", "community", 58, "guided",
    "Social media coordinator creating and managing content for a marketing analytics platform.",
    ["Social media management experience", "Analytics awareness", "Content creation skills"],
    ["Creative writer who also understands data and analytics", "Experience marketing tech products at HZL Studio", "Strong voice with platform-specific content instincts"],
    "I create social content for a tech brand at HZL Studio, so I understand how to make analytics accessible and engaging. My creative writing training ensures quality, and my tech background means I can speak authentically about your product. I'd bring Northbeam a social media coordinator with both creative and analytical fluency."),

  job(30, "Social Media Coordinator (Contract)", "Starface World", "Remote", true,
    "https://www.starface.world/careers", "community", 55, "guided",
    "Contract social media coordinator creating playful, brand-aligned content for a Gen-Z skincare brand.",
    ["Social media portfolio", "Understanding of Gen-Z culture", "Creative voice"],
    ["22-year-old creative with an authentic Gen-Z voice", "Strong visual and written storytelling skills from theatre background", "Culturally fluent with an engaging, playful creative style"],
    "I'm 22 and I've been building creative brands since Edinburgh Fringe. My voice is authentically Gen-Z, but my craft is professionally trained. I'd bring Starface a social coordinator who gets the culture because I live in it, with the creative skills to make content that truly pops."),

  job(31, "Social & Community Manager", "Sunrise Group", "Remote", true,
    "https://job-boards.greenhouse.io/sunriseunitedstatesinc/jobs/5127062008", "community", 58, "one-click",
    "Social and community manager building engaged communities and managing brand presence across channels.",
    ["Community management experience", "Social media skills", "Brand voice development"],
    ["Experience building communities around creative and tech projects", "Strong brand voice development skills from HZL Studio", "Producer's instinct for engagement and audience management"],
    "I build communities and develop brand voices. At HZL Studio, I've shaped how an AI brand communicates with its audience, and as a theatre producer, I've built engaged communities around creative work. I'd bring Sunrise a social and community manager with both creative instinct and strategic thinking."),

  job(32, "Social Media Content Specialist", "AllTrails", "Remote", true,
    "https://jobs.lever.co/alltrails/bf0ca92b-3e98-4a2a-b195-005565e82383", "community", 57, "one-click",
    "Content specialist creating engaging social media content for AllTrails' outdoor enthusiast community.",
    ["Content creation experience", "Social media platform expertise", "Visual storytelling"],
    ["Creative writer with strong visual storytelling skills", "Content creator with professional production experience", "Engaging voice that connects with community-driven audiences"],
    "I create content that builds community. My theatre production background gives me visual storytelling instincts, and my writing training ensures every piece of content has craft and purpose. I'd bring AllTrails a content specialist who knows how to engage passionate communities."),

  job(33, "Social Media Manager", "Remote.com", "Remote", true,
    "https://job-boards.greenhouse.io/remotecom/jobs/6530882003", "community", 55, "one-click",
    "Social media manager developing and executing social strategy for Remote.com's global HR platform.",
    ["Social media management experience", "B2B marketing awareness", "Global perspective"],
    ["International perspective with German fluency and Edinburgh Fringe experience", "Strategic thinker with founder-level understanding of brand building", "Strong writer who can translate complex HR/tech topics into engaging content"],
    "I bring a global perspective -- I speak German, I've produced work in Edinburgh, and I build tech products remotely. I understand Remote.com's audience because I live the remote-first, globally connected life your brand champions. I'd bring strategic social media thinking with international cultural fluency."),

  job(34, "Social & Community Manager", "Bitly", "Remote", true,
    "https://job-boards.greenhouse.io/bitly/jobs/4781735101", "community", 56, "one-click",
    "Social and community manager growing Bitly's brand presence and developer community engagement.",
    ["Community management experience", "Social media strategy", "Developer community familiarity"],
    ["Tech founder who understands developer communities", "Strong writer with brand voice development experience", "Community builder across creative and technical audiences"],
    "I bridge creative and technical communities as a playwright who builds AI systems. I understand developer audiences from the inside, and I know how to craft brand voices that resonate. I'd bring Bitly a community manager who can engage both technical and creative audiences authentically."),

  job(35, "Community Manager", "The Dispatch", "Remote", true,
    "https://jobs.lever.co/thedispatch/78a15265-74ba-49ef-af93-371c092f2581", "community", 60, "one-click",
    "Community manager fostering engaged readership and discussion for The Dispatch's journalism platform.",
    ["Community management experience", "Interest in media/journalism", "Strong communication skills"],
    ["Writer and producer who understands editorial communities", "Strong communicator trained in theatre and public engagement", "Passionate about quality journalism and informed discourse"],
    "I'm a professional writer who cares about discourse. My theatre background taught me to engage audiences thoughtfully, and my editorial instinct helps me understand what makes a journalism community thrive. I'd bring The Dispatch a community manager who values quality conversation."),

  job(36, "Junior Community Manager", "Edelman", "Remote", true,
    "https://jobs.lever.co/djeholdings/6c47f2cf-0367-4fe9-b0a8-ad5f311d77cc", "community", 58, "one-click",
    "Junior community manager supporting Edelman's digital PR and community engagement initiatives for enterprise clients.",
    ["Interest in PR/communications", "Community engagement skills", "Strong writing ability"],
    ["Professional communicator with theatre and editorial training", "Strong writer with brand voice adaptability", "Young, digitally fluent professional with cultural awareness"],
    "I'm a trained communicator -- theatre taught me to engage audiences, and building tech products taught me to listen to communities. I'd bring Edelman a junior community manager with professional writing skills, digital fluency, and a genuine instinct for fostering engagement."),

  job(37, "Content & Social Media Lead", "SpotHopper", "Remote", true,
    "https://job-boards.greenhouse.io/spothopper/jobs/4051229009", "community", 55, "one-click",
    "Lead content and social media strategy for SpotHopper's restaurant technology platform.",
    ["Content strategy experience", "Social media expertise", "Restaurant/hospitality interest"],
    ["Strategic content creator with founder-level experience", "Strong writer who can lead content initiatives", "Producer's organizational skills for managing content operations"],
    "I lead content initiatives at HZL Studio, from strategy to execution. My writing is professional and my organizational skills come from producing theatre. I'd bring SpotHopper a content lead who can both strategize and execute with creative precision."),

  // ─── DEVREL ────────────────────────────────────────────────────
  job(38, "DevRel & Community Manager", "SuperAnnotate", "Remote", true,
    "https://jobs.lever.co/superannotate/33d4b6f1-3209-420e-b226-58bfd8e464d6", "devrel", 62, "one-click",
    "Developer relations and community manager role bridging SuperAnnotate's AI annotation platform with its developer community.",
    ["Developer community experience", "Technical writing ability", "Public speaking skills"],
    ["Technical founder who builds AI tools -- authentic developer credibility", "Professional speaker and performer with theatre training", "Strong technical writer who can create documentation and tutorials"],
    "I'm a technical founder and trained performer -- I can demo a product, write its docs, and engage its community. At HZL Studio, I build AI tools and communicate about them; my theatre training makes me a natural presenter. I'd bring SuperAnnotate a DevRel who's both technically credible and genuinely engaging."),

  job(39, "New Grad SWE", "Mistral AI", "Paris, France", false,
    "https://jobs.lever.co/mistral/cf4616fc-977a-475c-bb2e-eb46a2c4a94f", "devrel", 45, "one-click",
    "New graduate software engineering role at Mistral AI, working on frontier large language models.",
    ["CS degree or equivalent", "Strong programming fundamentals", "Interest in AI/ML"],
    ["Self-taught engineer who ships AI products at HZL Studio", "Recent Fordham graduate with strong fundamentals", "Bilingual with European experience (German fluency)"],
    "I'm a recent graduate who builds AI products. At HZL Studio, I've shipped full-stack AI tools, and my German fluency and international experience (Edinburgh Fringe) give me comfort working in European contexts. I'd bring Mistral a new grad who already ships AI products."),

  // ─── IMMEDIATE INCOME ──────────────────────────────────────────
  job(40, "AI Creative Writing Trainer", "Outlier", "Remote", true,
    "https://boards.greenhouse.io/outlier/jobs/4289692005", "general", 75, "one-click",
    "Train AI models by providing expert creative writing feedback, evaluations, and demonstrations. Flexible remote work.",
    ["Professional creative writing experience", "Strong analytical skills", "Attention to detail"],
    ["Professional playwright with Edinburgh Fringe and Juilliard credentials", "AI builder who understands how models learn and improve", "Expert writer who can evaluate and improve AI-generated text"],
    "I'm a professional playwright and AI builder -- I write at a professional level and I understand how language models learn. This combination makes me an ideal AI writing trainer. I can evaluate AI text with a writer's precision and a technologist's understanding of what feedback actually improves model performance.",
    "$30-60/hr"),

  job(41, "AI Content Editor Tier 1", "Outlier AI", "Remote", true,
    "https://job-boards.greenhouse.io/outlierai/jobs/4409507005", "general", 72, "one-click",
    "Edit and evaluate AI-generated content for quality, accuracy, and style. Flexible hours, remote.",
    ["Strong editing skills", "Content evaluation experience", "Attention to detail"],
    ["Professional writer and editor with trained craft", "AI builder who understands model behavior and output quality", "Meticulous editor with a playwright's precision"],
    "I edit with a playwright's precision and evaluate AI output with a builder's insight. My professional writing credentials and AI systems experience make me a strong content editor who understands both what good writing looks like and how to improve model output."),

  job(42, "Copywriter / AI Trainer", "DataAnnotation", "Remote", true,
    "https://www.dataannotation.tech", "general", 70, "guided",
    "Provide expert copywriting feedback and training data for AI model improvement. Flexible remote contract work.",
    ["Professional writing experience", "Copywriting skills", "AI/tech familiarity"],
    ["Professional writer with diverse portfolio across theatre, tech, and brand copy", "AI builder who understands training data quality", "Versatile copywriter who can evaluate across styles and formats"],
    "I write professionally across formats -- plays, tech content, brand copy -- and I build AI systems. I understand what good training data looks like because I've built products that depend on it. I'd bring DataAnnotation a trainer with both writing expertise and AI fluency."),

  job(43, "RLHF Creative Writer", "Scale AI", "Remote", true,
    "https://scale.com/careers", "general", 68, "guided",
    "Creative writer providing RLHF (reinforcement learning from human feedback) data to improve AI model outputs.",
    ["Creative writing experience", "Understanding of AI/ML concepts", "Strong analytical skills"],
    ["Professional playwright who understands narrative craft at a deep level", "AI builder who understands RLHF and model improvement", "Expert writer who can demonstrate and evaluate creative quality"],
    "I'm a professional playwright and AI builder. I understand RLHF not just as a concept but as a practitioner -- I work with language models daily at HZL Studio. My creative writing credentials (Edinburgh Fringe, Juilliard) give me the expertise to provide high-quality human feedback on creative output."),

  job(44, "Project Lead - Alignerr", "Labelbox", "Remote", true,
    "https://job-boards.greenhouse.io/labelbox/jobs/4769508007", "general", 60, "one-click",
    "Lead annotation projects for Labelbox's Alignerr AI alignment platform, managing quality and workflows.",
    ["Project management experience", "AI/ML familiarity", "Leadership skills"],
    ["Founder with project leadership experience at HZL Studio", "Producer who manages complex projects (Edinburgh Fringe)", "AI builder who understands alignment and data quality"],
    "I lead projects as a founder and producer. At HZL Studio, I manage AI product development; at Edinburgh Fringe, I've produced theatre. Both require the same skills -- quality management, timeline adherence, and team coordination. I'd bring Labelbox a project lead who understands both AI and how to ship."),

  // ─── ANTHROPIC ROLES ───────────────────────────────────────────
  job(45, "AI Safety Fellow", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5023394008", "ai-safety", 78, "one-click",
    "Fellowship focused on AI safety research, policy, and alignment at Anthropic.",
    ["Interest in AI safety", "Strong analytical skills", "Technical or policy background"],
    ["AI product founder who thinks about safety in practice, not just theory", "Interdisciplinary background bridging humanities and technology", "Young builder with a stake in getting AI right"],
    "I build AI products and I care deeply about safety. At HZL Studio, every design decision involves thinking about how AI interacts with young learners. I'd bring Anthropic a fellow whose safety perspective comes from actually deploying AI responsibly."),

  job(46, "AI Security Fellow", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100001008", "ai-safety", 70, "one-click",
    "Fellowship exploring AI security challenges, adversarial robustness, and system integrity at Anthropic.",
    ["Security or AI background", "Analytical mindset", "Research interest"],
    ["AI builder who tests and secures AI systems at HZL Studio", "Creative problem-solver with red-teaming instincts from theatre training", "Technical practitioner with a security-conscious development approach"],
    "I build AI systems with a security-first mindset. At HZL Studio, I test my own products for failure modes and vulnerabilities. My theatre training taught me to think from every angle -- a skill that translates directly to adversarial thinking about AI security."),

  job(47, "Technical Writer (Contract)", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100002008", "copywriting", 68, "one-click",
    "Contract technical writer creating documentation, guides, and educational content for Anthropic's AI products.",
    ["Technical writing experience", "AI/ML familiarity", "Clear, precise prose"],
    ["Professional writer with both creative and technical fluency", "AI builder who can write documentation from practitioner experience", "Strong editorial craft trained at Juilliard and Edinburgh Fringe"],
    "I write professionally and I build AI systems. My technical documentation comes from practitioner experience -- I've written docs for tools I've built at HZL Studio. I'd bring Anthropic a technical writer whose clarity comes from genuine understanding, not just research."),

  job(48, "Editorial, Economic & Societal Impacts", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100003008", "copywriting", 65, "one-click",
    "Editorial role exploring AI's economic and societal impacts through research communications and public-facing content.",
    ["Strong writing and editorial skills", "Interest in AI policy", "Research communication experience"],
    ["Writer and thinker at the intersection of AI and society", "Founder who sees AI's societal impact firsthand through education", "Editorial craft from professional theatre and writing background"],
    "I see AI's societal impact firsthand -- at HZL Studio, I build AI tools for education and think daily about how technology shapes learning. My editorial craft comes from professional writing, and my perspective comes from building the technology. I'd bring Anthropic an editorial voice grounded in practice."),

  job(49, "Program Manager, Student Outreach", "Anthropic", "San Francisco, CA", false,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100004008", "community", 62, "one-click",
    "Manage Anthropic's student outreach programs, connecting with universities and fostering the next generation of AI safety researchers.",
    ["Program management experience", "University/student community connections", "Communication skills"],
    ["Recent Fordham graduate with fresh perspective on student outreach", "Founder of an AI education company -- you know how to engage students", "Producer with program coordination experience"],
    "I'm a recent Fordham graduate who founded an AI education company. I understand students because I just was one, and I understand AI education because I build it. I'd bring Anthropic a program manager who can connect authentically with students and communicate AI safety's importance."),

  job(50, "Developer Education Lead", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100005008", "devrel", 58, "one-click",
    "Lead developer education initiatives, creating tutorials, courses, and documentation for Anthropic's API and tools.",
    ["Developer education experience", "Technical writing skills", "Teaching or curriculum design background"],
    ["Founder of an AI education platform -- you design learning experiences", "Technical builder who can write tutorials from real development experience", "Strong communicator with theatre training"],
    "I design education experiences for a living. At HZL Studio, I build AI-powered learning tools, which means I think about pedagogy and technical content every day. I'd bring Anthropic a developer education lead who understands both how developers learn and how to create effective educational content."),

  job(51, "Content Designer, Enterprise Growth", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100006008", "copywriting", 60, "one-click",
    "Design content experiences for Anthropic's enterprise growth initiatives, from onboarding to case studies.",
    ["Content design experience", "Enterprise/B2B awareness", "Strong writing skills"],
    ["Designer and writer who thinks about user experience holistically", "Technical fluency to write authentically about AI products", "Founder who understands growth and user acquisition"],
    "I design content experiences at HZL Studio, thinking about how every piece of content serves the user journey. My writing is professional, my design thinking is user-centered, and my technical fluency means I can write about AI products with authentic understanding. I'd bring Anthropic a content designer who thinks like a product person."),

  job(52, "Developer Relations Engineer", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100007008", "devrel", 55, "one-click",
    "DevRel engineer building sample applications, tutorials, and developer community resources for Anthropic's platform.",
    ["Software engineering skills", "Developer community experience", "Public communication skills"],
    ["Technical founder who builds with Anthropic's tools", "Strong public communicator with theatre training", "Builder who can create compelling demos and tutorials"],
    "I build with AI APIs daily at HZL Studio, and my theatre training makes me a natural communicator and demonstrator. I'd bring Anthropic a DevRel engineer who can both build compelling samples and present them with clarity and enthusiasm."),

  job(53, "Developer Relations, MCP", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100008008", "devrel", 55, "one-click",
    "Developer relations role focused on Anthropic's Model Context Protocol, growing adoption and developer community.",
    ["Developer relations experience", "Protocol/API familiarity", "Community building skills"],
    ["Technical builder familiar with Anthropic's ecosystem including MCP", "Community builder with both tech and creative audiences", "Strong communicator and presenter"],
    "I build with Anthropic's tools and understand the developer ecosystem. My technical work at HZL Studio and my community-building experience across creative and tech contexts make me effective at growing developer adoption. I'd bring MCP a DevRel who uses the tools and can champion them authentically."),

  job(54, "Design Engineer, Education Labs", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100009008", "general", 52, "one-click",
    "Design engineer building educational products and experiments at Anthropic's Education Labs.",
    ["Frontend engineering skills", "Design sensibility", "Education technology interest"],
    ["Founder of an AI education platform -- exact domain expertise", "Full-stack builder with strong frontend skills", "Design sensibility from theatre and production background"],
    "I build AI education products. At HZL Studio, I design and engineer learning tools that use AI responsibly, which is exactly what Education Labs does. My frontend skills, design sensibility, and domain expertise in AI education make me a strong fit for this role."),

  job(55, "Certification Development Lead", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100010008", "general", 48, "one-click",
    "Lead development of certification programs for Anthropic's AI tools and platforms.",
    ["Certification or curriculum design experience", "Program management skills", "Technical AI knowledge"],
    ["Education company founder with curriculum design experience", "Program manager with production coordination skills", "Technical builder who understands what practitioners need to learn"],
    "I design educational experiences at HZL Studio, and I understand certification from a practitioner's perspective. I'd bring Anthropic a certification lead who can design programs that genuinely prepare people to use AI tools effectively."),

  job(56, "Research Engineer, Frontier Red Team Autonomy", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100011008", "ai-safety", 42, "one-click",
    "Research engineering role on Anthropic's Frontier Red Team, testing autonomous AI systems for safety.",
    ["Strong engineering skills", "AI safety research interest", "Systems thinking"],
    ["AI builder with systems-level thinking from HZL Studio", "Creative problem-solver with unconventional testing instincts", "Passionate about AI safety and responsible deployment"],
    "I build and test AI systems at HZL Studio, and I think creatively about failure modes. While my background is non-traditional for research engineering, my founder-level understanding of AI systems and my creative problem-solving skills could bring a fresh perspective to red teaming."),

  job(57, "Research Engineer, Societal Impacts", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100012008", "ai-safety", 45, "one-click",
    "Research engineering role studying how AI systems impact society, with focus on education, labor, and equity.",
    ["Research methodology skills", "AI/ML engineering ability", "Interest in societal impacts"],
    ["AI education founder who sees societal impact firsthand", "Interdisciplinary thinker bridging humanities and technology", "Builder with real-world perspective on AI deployment"],
    "I see AI's societal impact firsthand. At HZL Studio, I build AI tools for education and think about equity, access, and impact every day. My interdisciplinary background and hands-on experience give me a perspective on societal impacts that's grounded in practice."),

  job(58, "Research Engineer, AI Observability", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100013008", "general", 40, "one-click",
    "Research engineering role building tools and systems for observing and understanding AI model behavior.",
    ["Strong engineering skills", "ML systems experience", "Observability/monitoring interest"],
    ["AI builder who monitors and observes model behavior in production", "Systems thinker with full-stack engineering experience", "Founder who understands the importance of AI observability"],
    "I observe AI behavior in production at HZL Studio, monitoring how models perform and where they fail. While this role requires deeper ML expertise than I currently have, my practical experience with AI observability and my engineering skills provide a foundation to grow from."),

  job(59, "Applied Safety Research Engineer, Safeguards", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100014008", "ai-safety", 42, "one-click",
    "Applied research engineering role building safety safeguards for Anthropic's AI systems.",
    ["ML engineering experience", "Safety research interest", "Strong programming skills"],
    ["AI builder who implements safety measures in production", "Passionate about responsible AI from education context", "Technical practitioner with safety-first development approach"],
    "I build AI tools for young learners at HZL Studio, which means safety isn't optional -- it's the first requirement. My practical experience implementing AI safeguards and my passion for responsible AI make me a motivated candidate, even as I grow into the deeper ML skills this role requires."),

  job(60, "ML Research Engineer, Safeguards", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100015008", "ai-safety", 38, "one-click",
    "ML research engineering role developing machine learning approaches to AI safety and content safeguards.",
    ["ML research experience", "Strong Python/PyTorch skills", "Publication record preferred"],
    ["AI builder with practical ML experience", "Self-taught ML practitioner with strong fundamentals", "Passionate about AI safety from education deployment context"],
    "I'm an AI builder with a deep commitment to safety. While my ML research credentials are still developing, my practical experience building and deploying AI at HZL Studio gives me an applied perspective on safeguards. I learn fast, build responsibly, and care deeply about this work."),

  job(61, "Privacy Research Engineer, Safeguards", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100016008", "ai-safety", 45, "one-click",
    "Research engineering role focused on privacy-preserving techniques for AI systems and user data protection.",
    ["Privacy engineering experience", "ML/AI background", "Security mindset"],
    ["AI builder who handles student data with strict privacy requirements", "Security-conscious developer from education context", "Technical practitioner who takes privacy seriously in production"],
    "I handle student data at HZL Studio, which means privacy isn't abstract -- it's a daily engineering requirement. My experience building privacy-conscious AI systems for education gives me a practical foundation for privacy research engineering at Anthropic."),

  job(62, "Research Engineer, Virtual Collaborator", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100017008", "general", 40, "one-click",
    "Research engineering role building AI systems that collaborate with humans on complex tasks.",
    ["Strong engineering skills", "HCI research interest", "AI systems experience"],
    ["AI builder who designs human-AI collaboration at HZL Studio", "Theatre collaborator who understands human interaction deeply", "Full-stack engineer with UX sensibility"],
    "I design human-AI collaboration at HZL Studio, building tools where AI assists learners rather than replacing human interaction. My theatre background gives me deep insight into human collaboration, and my engineering skills let me build systems that support it."),

  job(63, "Research Engineer, Agents", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100018008", "general", 38, "one-click",
    "Research engineering role building and improving AI agent systems at Anthropic.",
    ["Strong software engineering", "AI agent systems experience", "Research mindset"],
    ["AI builder working with agent architectures at HZL Studio", "Self-taught engineer with rapid learning trajectory", "Practical experience deploying AI agents in production"],
    "I build AI agent systems at HZL Studio. While my research engineering credentials are developing, my practical experience with AI agents in production provides useful grounding. I'd bring Anthropic an engineer who ships agent systems and learns fast."),

  job(64, "Research Scientist, Societal Impacts", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100019008", "ai-safety", 40, "one-click",
    "Research scientist studying AI's societal impacts, contributing to policy and responsible deployment at Anthropic.",
    ["PhD preferred", "Research publication record", "AI policy knowledge"],
    ["AI education founder with firsthand societal impact experience", "Interdisciplinary perspective spanning humanities and technology", "Young thinker at the intersection of AI, education, and equity"],
    "I see AI's societal impact through the lens of education and equity every day at HZL Studio. While I don't have a PhD, my interdisciplinary background and practical experience deploying AI for societal benefit give me a grounded perspective on impacts research."),

  job(65, "Editorial, AI for Science", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100020008", "copywriting", 60, "one-click",
    "Editorial role communicating Anthropic's AI for Science initiatives through research summaries, blog posts, and public content.",
    ["Strong science writing", "Editorial experience", "AI/ML familiarity"],
    ["Professional writer with editorial craft and technical fluency", "AI builder who can write about technology from practitioner experience", "Strong communicator trained in theatre and creative writing"],
    "I write about AI from the inside. As a professional writer and AI builder, I can communicate complex research with both accuracy and editorial craft. I'd bring Anthropic's AI for Science team an editorial voice that's technically informed and beautifully written."),

  job(66, "Developer Relations Lead", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100021008", "devrel", 45, "one-click",
    "Lead Anthropic's developer relations strategy, building community and resources for the developer ecosystem.",
    ["DevRel leadership experience", "Technical background", "Community strategy expertise"],
    ["Technical founder with developer community experience", "Strong public communicator with theatre training", "Builder who uses Anthropic's tools and understands the developer experience"],
    "I build with Anthropic's tools and understand the developer experience firsthand. While a lead role requires more DevRel experience than I currently have, my founder experience, technical skills, and communication abilities provide a strong foundation. I'd grow into this role with intensity and care."),

  job(67, "Research Engineer, Alignment Science", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100022008", "ai-safety", 38, "one-click",
    "Research engineering role contributing to Anthropic's alignment science research agenda.",
    ["Strong ML engineering skills", "Alignment research familiarity", "Research contribution record"],
    ["AI builder passionate about alignment", "Self-taught ML practitioner with rapid learning", "Practical perspective on how AI systems behave in deployment"],
    "I'm passionate about alignment and I build AI systems in production. My practical experience at HZL Studio gives me a grounded perspective on how AI behaves in real deployment, which I believe is valuable context for alignment research."),

  job(68, "Research Engineer, Cybersecurity RL", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100023008", "ai-safety", 35, "one-click",
    "Research engineering role applying reinforcement learning to cybersecurity challenges in AI systems.",
    ["RL research experience", "Cybersecurity knowledge", "Strong engineering skills"],
    ["AI builder with security-conscious development practices", "Self-taught engineer who learns fast across domains", "Practical systems experience from founding HZL Studio"],
    "I build secure AI systems at HZL Studio and I learn fast. While RL and cybersecurity research require deeper specialization than I currently have, my security-conscious engineering practices and rapid learning trajectory make me a motivated candidate ready to grow."),

  job(69, "Research Engineer, Frontier Red Team Cyber", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100024008", "ai-safety", 35, "one-click",
    "Research engineering role on Anthropic's Frontier Red Team focused on cyber capabilities evaluation.",
    ["Security research experience", "AI/ML systems knowledge", "Adversarial thinking"],
    ["Creative adversarial thinker with theatre-trained perspective-shifting", "AI systems builder who tests for vulnerabilities", "Security-minded developer from education deployment context"],
    "I think adversarially by training -- theatre teaches you to inhabit different perspectives, and building AI for kids teaches you to think about every possible failure mode. While this role requires deeper security research credentials, my creative adversarial thinking and AI systems experience provide a useful foundation."),

  // ─── ADDITIONAL COPYWRITER/CONTENT ROLES (70-75) ──────────────
  job(70, "Junior Content Writer", "Jasper AI", "Remote", true,
    "https://www.jasper.ai/careers", "copywriting", 62, "guided",
    "Junior content writer creating blog posts, tutorials, and marketing content for Jasper's AI writing platform.",
    ["Strong writing skills", "AI/tech interest", "Content marketing awareness"],
    ["Professional writer who builds AI tools -- authentic voice for an AI writing company", "Editorial craft from theatre and Juilliard training", "Young, AI-native perspective on content creation"],
    "I write and I build AI writing tools. That combination makes me an authentic voice for Jasper -- I understand your product because I build similar tools at HZL Studio. My professional writing credentials ensure quality, and my AI fluency ensures authenticity."),

  job(71, "Junior Copywriter", "Runway ML", "Remote", true,
    "https://runwayml.com/careers", "copywriting", 64, "guided",
    "Junior copywriter crafting brand and product copy for Runway's AI creative tools platform.",
    ["Creative writing portfolio", "Interest in AI/creative tools", "Brand voice adaptability"],
    ["Creative technologist who uses AI tools for artistic work", "Professional writer with production credits", "Young creative at the intersection of AI and art"],
    "I'm a creative who uses AI tools and a technologist who understands them. My Edinburgh Fringe credits and HZL Studio work show I live at the intersection of creativity and technology. I'd bring Runway a copywriter who genuinely understands both your product and your audience."),

  job(72, "Content Writer", "Hugging Face", "Remote", true,
    "https://huggingface.co/careers", "copywriting", 60, "guided",
    "Content writer creating educational content, blog posts, and documentation for Hugging Face's open-source AI platform.",
    ["Technical writing ability", "AI/ML knowledge", "Community engagement skills"],
    ["AI builder who can write technical content from experience", "Strong writer with editorial craft", "Community-minded creator who understands open-source culture"],
    "I build AI tools and I write about them with a professional writer's craft. My technical content comes from practitioner experience, not just research. I'd bring Hugging Face a content writer who understands your community because I'm part of it."),

  job(73, "Junior Brand Copywriter", "Cohere", "Remote", true,
    "https://cohere.com/careers", "copywriting", 58, "guided",
    "Junior brand copywriter developing Cohere's voice across marketing materials, web content, and campaigns.",
    ["Brand writing portfolio", "Tech industry awareness", "Creative voice"],
    ["Professional writer with a distinctive, trainable voice", "Technical fluency from building AI products", "Young creative with brand voice development experience"],
    "I develop brand voices for a living -- at HZL Studio and in theatre. My writing is distinctive but adaptable, and my AI fluency means I can write about enterprise AI with genuine understanding. I'd bring Cohere a brand voice that's both sophisticated and accessible."),

  job(74, "Content Strategist", "Stability AI", "Remote", true,
    "https://stability.ai/careers", "copywriting", 56, "guided",
    "Content strategist planning and creating content across Stability AI's marketing and education channels.",
    ["Content strategy experience", "AI/creative technology interest", "Writing portfolio"],
    ["Strategic thinker with founder-level content experience", "Creative technologist who understands AI art and generation", "Strong writer with editorial and production background"],
    "I strategize and create content at HZL Studio, thinking about how every piece serves users and business goals. My creative technology background and professional writing skills make me a content strategist who can plan and execute with equal skill."),

  job(75, "Junior Technical Copywriter", "Vercel", "Remote", true,
    "https://vercel.com/careers", "copywriting", 63, "guided",
    "Junior technical copywriter creating developer-facing content, documentation, and marketing copy for Vercel's platform.",
    ["Technical writing skills", "Web development familiarity", "Developer audience understanding"],
    ["Full-stack builder who ships on Vercel-adjacent technologies (Next.js)", "Professional writer with technical depth", "Developer who writes -- authentic voice for developer content"],
    "I ship Next.js applications and I write professionally. That combination -- real development experience plus editorial craft -- is exactly what developer-facing content requires. I'd bring Vercel a technical copywriter who uses your tools and can write about them with authentic authority."),

  // ─── ADDITIONAL SOCIAL MEDIA ROLES (76-80) ────────────────────
  job(76, "Social Media Coordinator", "Notion", "Remote", true,
    "https://www.notion.so/careers", "community", 58, "guided",
    "Social media coordinator managing Notion's community-driven social presence across platforms.",
    ["Social media experience", "Content creation skills", "Community engagement"],
    ["Power user of productivity tools with creative perspective", "Young, digitally native voice with cultural fluency", "Content creator with professional writing training"],
    "I'm a productivity-obsessed creative who builds systems for everything. My social media instincts are informed by professional writing training, and my voice is authentically young and digitally native. I'd bring Notion a social coordinator who understands your community because I'm part of it."),

  job(77, "Social Media Manager", "Replit", "Remote", true,
    "https://replit.com/careers", "community", 55, "guided",
    "Social media manager growing Replit's developer community presence and brand awareness.",
    ["Social media strategy experience", "Developer community familiarity", "Content creation"],
    ["Technical builder who understands developer culture", "Creative writer with engaging social media voice", "Young technologist with authentic digital presence"],
    "I'm a builder in the developer community, and I know how to engage technical audiences on social media. My creative background gives me the content skills, and my technical work gives me the credibility. I'd bring Replit a social media manager who speaks developer fluently."),

  job(78, "Social Content Creator", "Figma", "Remote", true,
    "https://www.figma.com/careers", "community", 56, "guided",
    "Social content creator developing engaging content for Figma's design community across social platforms.",
    ["Content creation portfolio", "Design community awareness", "Visual storytelling"],
    ["Visual storyteller with theatre production experience", "Creative technologist who understands design tools", "Young creative with strong social media instincts"],
    "I create visual stories -- in theatre, in tech products, and on social media. My production background gives me visual instincts, and my tech work gives me understanding of design communities. I'd bring Figma a content creator who can engage designers with creative, visually compelling content."),

  job(79, "Social Media Specialist", "Linear", "Remote", true,
    "https://linear.app/careers", "community", 52, "guided",
    "Social media specialist managing Linear's brand presence and engaging the developer tool community.",
    ["Social media experience", "B2B/developer tool familiarity", "Strong writing"],
    ["Developer tool user with authentic perspective", "Strong writer with brand voice skills", "Young professional with digital-native social media instincts"],
    "I use developer tools daily and I know how to talk about them on social media. My writing training ensures every post has craft, and my technical background means I engage authentically with the developer tool community. I'd bring Linear a social specialist who understands your audience."),

  job(80, "Social Media Coordinator", "Perplexity AI", "Remote", true,
    "https://www.perplexity.ai/careers", "community", 57, "guided",
    "Social media coordinator growing Perplexity AI's presence and community engagement across platforms.",
    ["Social media management experience", "AI/tech interest", "Creative content skills"],
    ["AI builder who can speak authentically about AI products", "Creative writer with engaging social voice", "Young, digitally native professional with AI fluency"],
    "I build AI products and I know how to talk about them in ways that resonate. My creative writing background ensures engaging content, and my AI fluency means I can communicate about your product with genuine understanding. I'd bring Perplexity a social coordinator who lives in the AI ecosystem."),

  // ─── ADDITIONAL AI TRAINING/ANNOTATION ROLES (81-85) ──────────
  job(81, "AI Writing Quality Evaluator", "Surge AI", "Remote", true,
    "https://www.surgehq.ai/careers", "general", 68, "guided",
    "Evaluate AI-generated writing for quality, coherence, and safety. Flexible remote work with competitive pay.",
    ["Professional writing experience", "Attention to detail", "Analytical skills"],
    ["Professional playwright with expert-level writing evaluation skills", "AI builder who understands model behavior", "Meticulous editor with trained craft"],
    "I evaluate writing at a professional level -- my playwright's training and AI building experience give me both the literary expertise and technical understanding to assess AI writing quality with precision."),

  job(82, "Creative Writing AI Trainer", "Appen", "Remote", true,
    "https://appen.com/careers", "general", 65, "guided",
    "Provide expert creative writing demonstrations and evaluations to train AI models. Flexible schedule.",
    ["Creative writing credentials", "AI familiarity", "Strong analytical skills"],
    ["Professional playwright with Edinburgh Fringe and Juilliard credentials", "AI builder who understands training data quality", "Expert writer across multiple genres and formats"],
    "I'm a professional playwright and AI builder. My creative writing credentials (Edinburgh Fringe, Juilliard) give me the expertise to provide high-quality training data, and my AI experience means I understand what model improvement requires."),

  job(83, "AI Content Reviewer", "Invisible Technologies", "Remote", true,
    "https://www.invisible.co/careers", "general", 62, "guided",
    "Review and curate AI-generated content for accuracy, quality, and brand safety across client projects.",
    ["Content review experience", "Strong editorial judgment", "Attention to detail"],
    ["Professional writer with strong editorial judgment", "AI builder who understands content generation", "Detail-oriented reviewer with trained craft"],
    "My editorial judgment comes from professional writing training and my understanding of AI content comes from building AI systems. I'd bring Invisible Technologies a content reviewer with both literary expertise and technical insight."),

  job(84, "RLHF Data Specialist", "Prolific", "Remote", true,
    "https://www.prolific.com/careers", "general", 63, "guided",
    "Specialist role providing high-quality RLHF feedback for AI model training across creative and analytical tasks.",
    ["Subject matter expertise in writing/creative arts", "Analytical thinking", "AI familiarity"],
    ["Professional writer with expert-level creative feedback capabilities", "AI builder who understands RLHF methodology", "Interdisciplinary thinker with both creative and analytical skills"],
    "I provide expert creative feedback professionally and I understand RLHF from a builder's perspective. My writing credentials and AI experience make me an ideal RLHF specialist for creative and analytical tasks."),

  job(85, "AI Writing Coach / Annotator", "Cohere", "Remote", true,
    "https://cohere.com/careers/annotator", "general", 64, "guided",
    "Coach AI models through expert writing demonstrations, annotations, and quality evaluations.",
    ["Professional writing background", "Teaching or coaching experience", "AI interest"],
    ["Professional writer with Juilliard and Edinburgh Fringe training", "Education experience from founding HZL Studio's learning platform", "AI builder who understands model learning from training data"],
    "I coach writers and AI alike. My professional writing credentials and education experience at HZL Studio make me effective at demonstrating quality writing and providing the feedback AI models need to improve."),

  // ─── ADDITIONAL EDITORIAL/CONTENT STRATEGIST ROLES (86-90) ────
  job(86, "Content Strategist", "Notion", "Remote", true,
    "https://www.notion.so/careers/content", "copywriting", 60, "guided",
    "Content strategist developing Notion's editorial voice across blog, help center, and marketing content.",
    ["Content strategy portfolio", "Editorial experience", "Tech product familiarity"],
    ["Strategic content creator with founder-level experience", "Professional writer with editorial craft", "Power user of productivity tools with insider perspective"],
    "I create strategic content at HZL Studio and I'm a devoted Notion user. My professional writing background and product-building experience give me both the editorial craft and strategic thinking this role demands."),

  job(87, "Editorial Associate", "The Verge (Vox Media)", "Remote", true,
    "https://www.voxmedia.com/careers", "copywriting", 62, "guided",
    "Editorial associate covering technology and culture at The Verge, writing news, features, and analysis.",
    ["Journalism or editorial experience", "Technology knowledge", "Fast, accurate writing"],
    ["Writer at the intersection of technology and culture", "AI builder with insider perspective on tech stories", "Young voice with professional writing credentials"],
    "I write about technology from the inside -- I build AI products and I have a professional writer's craft. My perspective as a young technologist and playwright gives me a unique editorial voice for covering tech and culture. I'd bring The Verge writing that's both technically informed and culturally aware."),

  job(88, "Junior Editor, AI & Tech", "Wired (Conde Nast)", "Remote", true,
    "https://www.condenast.com/careers", "copywriting", 58, "guided",
    "Junior editor working on AI and technology coverage at Wired, commissioning and editing feature stories.",
    ["Editorial experience", "Deep AI/tech knowledge", "Strong editorial judgment"],
    ["AI builder with editorial craft from professional writing background", "Deep tech knowledge from founding an AI company", "Young editor with both cultural awareness and technical fluency"],
    "I build AI systems and I write professionally -- that combination gives me editorial judgment that's both technically rigorous and culturally attuned. I'd bring Wired a junior editor who can evaluate AI stories with a builder's insight."),

  job(89, "Content Strategist", "OpenAI", "Remote", true,
    "https://openai.com/careers", "copywriting", 65, "guided",
    "Content strategist shaping OpenAI's public communications, educational content, and brand narrative.",
    ["Content strategy experience", "AI/ML familiarity", "Strong writing skills"],
    ["AI builder who writes about technology with practitioner authority", "Strategic thinker with founder-level content experience", "Professional writer with editorial craft"],
    "I build AI products and I write strategically about them. My content at HZL Studio serves users, grows awareness, and communicates complex ideas simply. I'd bring OpenAI a content strategist whose authority comes from building the technology, not just writing about it."),

  job(90, "Editorial Content Producer", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100025008", "copywriting", 58, "one-click",
    "Editorial content producer creating blog posts, research summaries, and public-facing content for Anthropic.",
    ["Editorial production experience", "AI/tech writing ability", "Content management skills"],
    ["Professional writer with editorial production experience from theatre", "AI builder who writes about technology authentically", "Strong editorial craft with technical depth"],
    "I produce editorial content at HZL Studio and I've produced creative work at Edinburgh Fringe. Both require the same skills -- editorial judgment, production management, and quality writing. I'd bring Anthropic an editorial producer with both creative craft and technical fluency."),

  // ─── ADDITIONAL JUNIOR FRONTEND/FULLSTACK ROLES (91-95) ───────
  job(91, "Junior Frontend Engineer", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100026008", "general", 50, "one-click",
    "Junior frontend engineer building user-facing interfaces for Anthropic's AI products.",
    ["React/TypeScript experience", "Strong UI skills", "AI product interest"],
    ["Full-stack builder with React/Next.js/TypeScript at HZL Studio", "Design sensibility from theatre and production background", "AI product builder with relevant domain experience"],
    "I build frontend interfaces for AI products at HZL Studio using React, Next.js, and TypeScript. My theatre background gives me design sensibility that most engineers lack. I'd bring Anthropic a frontend engineer who cares about how interfaces feel, not just how they function."),

  job(92, "Junior Fullstack Developer", "Replicate", "Remote", true,
    "https://replicate.com/careers", "general", 48, "guided",
    "Junior fullstack developer building Replicate's platform for running and deploying ML models.",
    ["Fullstack web development skills", "API design experience", "ML interest"],
    ["Full-stack AI product builder at HZL Studio", "Self-taught developer with rapid learning trajectory", "Experience building and deploying ML-powered applications"],
    "I build full-stack AI applications at HZL Studio. My self-taught engineering skills and rapid learning trajectory make me a strong junior developer ready to grow on a platform like Replicate."),

  job(93, "Frontend Developer", "Weights & Biases", "Remote", true,
    "https://wandb.ai/careers", "general", 47, "guided",
    "Frontend developer building data visualization and experiment tracking interfaces for ML practitioners.",
    ["React/TypeScript skills", "Data visualization experience", "ML tool familiarity"],
    ["Frontend builder with React/TypeScript experience", "Data-aware developer from AI product work", "Design sensibility from creative background"],
    "I build data-rich interfaces at HZL Studio and my creative background gives me strong visualization instincts. I'd bring W&B a frontend developer who can make complex ML data feel intuitive and beautiful."),

  job(94, "Junior Software Engineer", "Character AI", "Remote", true,
    "https://character.ai/careers", "general", 52, "guided",
    "Junior software engineer building features for Character AI's conversational AI platform.",
    ["Software engineering fundamentals", "Interest in conversational AI", "Strong problem-solving"],
    ["Conversational AI builder at HZL Studio", "Playwright who understands dialogue and character", "Full-stack developer with AI product experience"],
    "I build conversational AI tools and I write dialogue professionally. That combination -- technical engineering plus a playwright's understanding of conversation -- makes me a strong fit for Character AI. I'd bring both technical skills and unique domain insight."),

  job(95, "Junior Frontend Engineer", "Midjourney", "Remote", true,
    "https://www.midjourney.com/careers", "general", 45, "guided",
    "Junior frontend engineer building creative tools and user experiences for Midjourney's AI art platform.",
    ["Frontend development skills", "Creative tool experience", "UI/UX sensibility"],
    ["Creative technologist who builds AI-powered creative tools", "Frontend developer with strong design sensibility", "Artist and engineer at the intersection of AI and creativity"],
    "I build AI-powered creative tools at HZL Studio, working at the exact intersection of technology and creativity that Midjourney lives in. My frontend skills and creative background make me a natural fit for building interfaces for AI art."),

  // ─── ADDITIONAL COMMUNITY MANAGER ROLES (96-100) ──────────────
  job(96, "Community Manager", "Hugging Face", "Remote", true,
    "https://huggingface.co/careers/community", "community", 58, "guided",
    "Community manager fostering Hugging Face's open-source AI community, managing forums, events, and partnerships.",
    ["Community management experience", "AI/ML community familiarity", "Event coordination skills"],
    ["Technical builder active in the AI community", "Event producer with Edinburgh Fringe experience", "Strong communicator who bridges technical and creative audiences"],
    "I build AI tools and I build communities. My Edinburgh Fringe production experience gives me event coordination skills, and my AI work at HZL Studio gives me credibility in the ML community. I'd bring Hugging Face a community manager who's both technically fluent and operationally experienced."),

  job(97, "Community Lead", "LangChain", "Remote", true,
    "https://www.langchain.com/careers", "community", 55, "guided",
    "Community lead growing LangChain's developer community through content, events, and engagement programs.",
    ["Developer community experience", "Technical content creation", "Community strategy"],
    ["AI developer who uses LLM frameworks in production", "Community builder with creative and technical range", "Content creator with professional writing skills"],
    "I use LLM frameworks to build AI products at HZL Studio, and I know how to engage developer communities. My combination of technical credibility and communication skills makes me effective at growing developer communities from the inside."),

  job(98, "Community Manager", "Vercel", "Remote", true,
    "https://vercel.com/careers/community", "community", 53, "guided",
    "Community manager growing Vercel's developer community and supporting the Next.js ecosystem.",
    ["Community management skills", "Next.js/React familiarity", "Developer advocacy"],
    ["Next.js developer with real deployment experience", "Community builder with strong communication skills", "Technical creator active in the web development ecosystem"],
    "I ship Next.js applications and I'm active in the developer community. I'd bring Vercel a community manager who uses your platform daily and can engage developers with authentic credibility."),

  job(99, "Developer Community Coordinator", "Supabase", "Remote", true,
    "https://supabase.com/careers", "community", 52, "guided",
    "Coordinator supporting Supabase's developer community through content, events, and community programs.",
    ["Community coordination experience", "Backend/database familiarity", "Content creation skills"],
    ["Full-stack developer who understands backend and database technologies", "Community builder with event production experience", "Strong writer who can create engaging developer content"],
    "I build full-stack applications and I coordinate creative communities. My development experience with databases and backends gives me technical context, and my production background gives me event coordination skills. I'd bring Supabase a community coordinator who's both technical and organized."),

  job(100, "Community & Events Manager", "Anthropic", "San Francisco, CA", true,
    "https://job-boards.greenhouse.io/anthropic/jobs/5100027008", "community", 56, "one-click",
    "Community and events manager building Anthropic's external community presence and coordinating events.",
    ["Events management experience", "Community building skills", "AI industry knowledge"],
    ["Event producer with Edinburgh Fringe coordination experience", "AI builder with deep industry knowledge", "Strong communicator and community builder across audiences"],
    "I produce events and build communities. My Edinburgh Fringe production experience and HZL Studio community work give me both the logistics skills and the AI industry knowledge this role requires. I'd bring Anthropic a community and events manager who understands your mission and can execute with precision."),
];
