import { Profile } from "./types";

export const DEFAULT_PROFILE: Profile = {
  name: "Ryann Lynn Murphy",
  email: "ryannlynncontact@gmail.com",
  phone: "",
  location: "New York, NY",
  linkedin: "linkedin.com/in/ryann-lynn-murphy",
  github: "github.com/ryannlynnmurphy",
  website: "ryannlynnmurphy.com",
  education: [
    {
      id: "edu-1",
      school: "Fordham University",
      degree: "BA",
      field: "Theatre — Performance & Playwriting",
      graduationYear: "2025",
      notes: "Full scholarship. Three produced plays. Managed theatre department operations including budgets, scheduling, and teams of 40-50.",
    },
  ],
  experience: [
    {
      id: "exp-1",
      title: "Founder & Lead Engineer",
      org: "HZL AI LLC",
      startDate: "2026-03",
      endDate: "present",
      description: "Founded AI studio in March 2026 with zero engineering background. Shipped five production systems in first month: Hazel (voice AI), HZL Academy (educational platform, patent pending), HZL Studio (hardware creative environment), Ryann Apply (job automation tool), and ryannlynnmurphy.com (interactive portfolio). Filed provisional patent #590420394-ABX covering dual-model verification architecture.",
    },
    {
      id: "exp-2",
      title: "Opinion Columnist",
      org: "The Fordham Observer",
      startDate: "2024-08",
      endDate: "2025-05",
      description: "Published editorial content on culture, arts, and social issues in AP Style for Fordham's student newspaper. Wrote under deadline for a real readership.",
    },
    {
      id: "exp-3",
      title: "Produced Playwright",
      org: "Edinburgh Fringe Festival",
      startDate: "2025-08",
      endDate: "2025-08",
      description: "Wrote, produced, and performed Grooming My Ass — a one-woman dark comedy — at the Edinburgh Fringe Festival. Crowdfunded production with Rogue Arts NYC. Previously previewed at Theatre Under St. Marks and The Tank.",
    },
    {
      id: "exp-4",
      title: "Playwright",
      org: "The Juilliard School",
      startDate: "2025-01",
      endDate: "2025-01",
      description: "SCOUTS received a professional reading at Juilliard. Play explores cycles of toxic masculinity in a Boy Scout camp. Directed by Juju Jaworski.",
    },
    {
      id: "exp-5",
      title: "Playwright & Lead Actor",
      org: "Fordham University Theatre",
      startDate: "2024-10",
      endDate: "2025-02",
      description: "Wrote and starred in Thoughts on Girlcock (thesis production, Feb 2025). Also produced SCOUTS (Oct 2024). Additional acting credits: Titania/Hippolyta in A Midsummer Night's Dream, Agatha (lead) in The Moors, Henry in Next to Normal, Timothy in Hand to God.",
    },
    {
      id: "exp-6",
      title: "Technical Theatre",
      org: "Fordham University",
      startDate: "2021",
      endDate: "2025",
      description: "Sound designer (2 productions), assistant lighting designer, theatrical electrician and technician. Managed production logistics for department.",
    },
    {
      id: "exp-7",
      title: "Freelance Web Designer",
      org: "Independent",
      startDate: "2026-03",
      endDate: "present",
      description: "Built custom portfolio websites for clients including actor portfolios with luxury dark aesthetics, custom typography, and responsive design.",
    },
  ],
  skills: [
    "Python",
    "JavaScript",
    "TypeScript",
    "Next.js",
    "React",
    "HTML/CSS",
    "Tailwind CSS",
    "Framer Motion",
    "Claude API",
    "Anthropic SDK",
    "Whisper STT",
    "ElevenLabs TTS",
    "Prompt Engineering",
    "Dual-Model Verification",
    "WebSocket",
    "OAuth2",
    "SQLite",
    "Puppeteer",
    "Cheerio",
    "Web Scraping",
    "SEO",
    "Raspberry Pi",
    "Linux",
    "Home Assistant",
    "Distributed Inference",
    "Git",
    "GitHub Pages",
    "Ollama",
    "Editorial Writing",
    "Playwriting",
    "Creative Writing",
    "AP Style",
    "Brand Voice",
    "Social Media",
    "Sound Design",
    "Production Management",
  ],
  languages: ["English", "German"],
  bioVariants: [
    {
      id: "bio-tech",
      label: "Tech-forward",
      text: "I'm a playwright who taught herself to code in March 2026 and shipped five production systems in my first month — including a voice AI running on a Raspberry Pi 5, a K-12 educational platform with a patent-pending dual-model verification architecture, a four-node distributed computing cluster, an AI-powered job automation tool, and an interactive portfolio site with a custom chatbot. I have a BA in Theatre from Fordham University on full scholarship, three produced plays (Edinburgh Fringe, Juilliard, Fordham), and a year of published editorial work at the Fordham Observer. I founded HZL AI LLC and I build things that don't exist yet.",
    },
    {
      id: "bio-creative",
      label: "Creative-forward",
      text: "Writer, producer, and technologist. I produced a one-woman show at the Edinburgh Fringe Festival, had a play read at Juilliard, wrote my university's thesis production and played the lead, and published an opinion column at the Fordham Observer. In March 2026 I taught myself to code and founded HZL AI LLC — shipping a voice assistant, an educational platform (patent pending), and a hardware creative production studio in a single month. I build AI tools that serve creative and educational purposes because I couldn't find the ones I needed.",
    },
    {
      id: "bio-hybrid",
      label: "Hybrid",
      text: "I bridge theatre and engineering. BA in Playwriting from Fordham on full scholarship, three produced plays, a year of published journalism — and in my first month of coding I shipped a local voice AI on Raspberry Pi, a patent-pending K-12 platform, a four-node computing cluster, and a job automation tool with Puppeteer-driven form filling. The reason I can do both is the same: I find where systems break and I build what's missing. Founded HZL AI LLC, March 2026.",
    },
    {
      id: "bio-founder",
      label: "Founder narrative",
      text: "I founded HZL AI LLC because I wanted to learn to code and nothing good existed to teach me. So I built it — HZL Academy, a K-12 educational platform with a patent-pending dual-model verification architecture. Then I built Hazel, a voice assistant on Raspberry Pi 5, because I wanted one that actually worked locally. Then I built the hardware studio to run it all on. Five production systems, one month, zero prior engineering experience. BA in Playwriting from Fordham, full scholarship. Edinburgh Fringe. Juilliard. I don't wait for tools to exist.",
    },
    {
      id: "bio-absurd-timeline",
      label: "The timeline is absurd",
      text: "In March 2026 I had never written a line of code. By April I had shipped a voice AI on Raspberry Pi 5 (Whisper, Claude API, ElevenLabs, OAuth2 integrations), a K-12 educational platform with a provisional patent, a four-node distributed computing cluster, an AI job automation tool with browser automation, and a portfolio site with a custom chatbot — and founded HZL AI LLC to house it all. I have a BA in Playwriting from Fordham on full scholarship, a play read at Juilliard, and a one-woman show at Edinburgh Fringe. The timeline is absurd. The work is real.",
    },
  ],
  coverLetterBlocks: [
    {
      id: "block-hazel",
      label: "Hazel — voice AI (detailed)",
      text: "I built Hazel from a bare Raspberry Pi 5 OS installation — a local-first voice assistant with Whisper for on-device speech recognition, Claude API with dynamic Haiku/Sonnet routing based on task complexity, ElevenLabs TTS, Gmail and Google Calendar OAuth2 integration, Home Assistant connectivity, Tavily real-time search, SQLite persistent memory, and a WebSocket backend I wrote in Python. I chose local-first architecture specifically because I modeled the threat of centralized data collection. The smart model routing — lightweight model for fast queries, heavier for complex reasoning — was a cost and latency optimization I designed after observing real usage patterns.",
      tags: ["ai-safety", "devrel", "fellowship", "general"],
    },
    {
      id: "block-academy",
      label: "HZL Academy — patent pending (detailed)",
      text: "HZL Academy is a K-12 educational platform built in Next.js with a patent-pending dual-model verification architecture (provisional patent #590420394-ABX). Two AI models cross-check each other's outputs before anything reaches a learner. I built that verification layer because I watched Claude produce confidently wrong educational content for children and decided no single model should be trusted unsupervised. The platform includes three-tier content routing — pre-built lessons served instantly, AI adapts only when needed, all AI output verified against source material — plus adaptive caching that makes the system faster with use and COPPA-compliant on-device data storage.",
      tags: ["ai-safety", "fellowship", "general"],
    },
    {
      id: "block-studio",
      label: "HZL Studio — hardware cluster",
      text: "I built HZL Studio, a four-node Raspberry Pi 5 cluster running distributed AI inference via exo, with five switchable creative modes (Game, Film, Music, Stream, Write), gigabit networking, PoE+ power, NVMe storage via PCIe, AMD GPU with ROCm, Focusrite Scarlett 4i4 audio interface, and solar-compatible architecture. Mode switching happens via voice command through Hazel or physical Stream Deck. The entire stack is open-source with zero vendor lock-in.",
      tags: ["devrel", "fellowship", "general"],
    },
    {
      id: "block-portfolio",
      label: "Portfolio site — interactive design",
      text: "My portfolio at ryannlynnmurphy.com is a pure HTML/CSS/vanilla JS site where the design IS the art piece — desktop renders as a CRT monitor with keyboard, mobile renders as an iPhone with notch. It includes a custom chatbot with 30+ conversational intents, a CRT power-on boot animation, binary code rain background, a Konami code easter egg triggering a multi-step glitch sequence, leaked data fragments, and full SEO (Open Graph, Twitter Cards, JSON-LD structured data, sitemaps). Deployed on GitHub Pages with a custom domain.",
      tags: ["devrel", "community", "fellowship", "general"],
    },
    {
      id: "block-ryann-apply",
      label: "Ryann Apply — job automation",
      text: "I built Ryann Apply, an AI-powered job application automation tool in Next.js with Tinder-style job discovery, automated Greenhouse and Lever board scraping, a profile-driven auto-fill system, Claude-powered cover letter generation with modular template blocks, Puppeteer browser automation for form detection and filling, and scheduled scraping via Windows Task Scheduler. The full pipeline: scrape boards, score and rank against my profile, generate tailored materials, detect form fields, fill, submit.",
      tags: ["devrel", "fellowship", "general"],
    },
    {
      id: "block-writing",
      label: "Writing credentials (full)",
      text: "I produced a one-woman dark comedy at the Edinburgh Fringe Festival, had SCOUTS read professionally at The Juilliard School, wrote and starred in my university's thesis production, and published an opinion column at the Fordham Observer for a year in AP Style. I've also previewed work at Theatre Under St. Marks and The Tank. I know how to write under deadline, for different audiences, at different lengths, and in different registers — editorial, dramatic, conversational, technical. That range is rare in any field.",
      tags: ["copywriting", "community", "devrel", "fellowship", "general"],
    },
    {
      id: "block-safety",
      label: "Why AI safety",
      text: "I am building AI products that will live in people's homes and teach children. The question of what these systems can be made to do by a motivated bad actor is one I think about every day. I built a dual-model verification system because I didn't trust a single model to be accurate for children's education. I chose local-first architecture for Hazel because I modeled the privacy threat of centralized voice data. I designed adversarial safeguards into my first AI systems before I knew what to call them. I would rather be on the side of finding failures before they ship.",
      tags: ["ai-safety", "fellowship"],
    },
    {
      id: "block-german",
      label: "German language",
      text: "I also speak German, which is directly relevant to your work on global audiences, international markets, and multilingual threat landscapes.",
      tags: ["ai-safety", "community", "general"],
    },
    {
      id: "block-timeline",
      label: "The absurd timeline",
      text: "I have been coding for one month. In that time I have shipped five production systems, filed a provisional patent, founded a company, and deployed a live portfolio. I am not claiming years of experience I don't have. I am claiming a rate of output that speaks for itself. The question is not whether I can learn your stack — it's how fast.",
      tags: ["ai-safety", "devrel", "fellowship", "general"],
    },
    {
      id: "block-production-mgmt",
      label: "Production management background",
      text: "Three years of theatre production gave me experience managing teams of 40-50 people, running budgets, coordinating logistics under hard deadlines, and shipping creative work on schedule. That is product management by another name. I know how to scope, schedule, and deliver.",
      tags: ["community", "fellowship", "general"],
    },
    {
      id: "block-patent",
      label: "Patent mention",
      text: "I filed provisional patent #590420394-ABX covering HZL Academy's dual-model verification architecture — the system where two AI models cross-check each other before serving content to learners. I am 22 and I have a patent filing. That is not typical for someone who learned to code a month ago.",
      tags: ["ai-safety", "fellowship", "general"],
    },
  ],
  resumePresets: [
    {
      id: "preset-safety",
      label: "AI / Safety",
      leadWith: ["exp-1", "block-hazel", "block-academy", "block-safety", "block-patent"],
      skills: ["Python", "Claude API", "Anthropic SDK", "Prompt Engineering", "Whisper STT", "Dual-Model Verification", "Raspberry Pi", "SQLite", "WebSocket"],
      defaultBioVariant: "bio-tech",
    },
    {
      id: "preset-copy",
      label: "Copywriting",
      leadWith: ["exp-2", "exp-3", "exp-4", "exp-5", "block-writing"],
      skills: ["Editorial Writing", "Playwriting", "Creative Writing", "AP Style", "Brand Voice", "Social Media", "SEO"],
      defaultBioVariant: "bio-creative",
    },
    {
      id: "preset-community",
      label: "Community / Social",
      leadWith: ["exp-2", "exp-3", "exp-1", "block-writing", "block-production-mgmt"],
      skills: ["Social Media", "Brand Voice", "Editorial Writing", "Creative Writing", "Production Management", "SEO"],
      defaultBioVariant: "bio-creative",
    },
    {
      id: "preset-devrel",
      label: "DevRel",
      leadWith: ["exp-1", "block-hazel", "block-portfolio", "block-writing", "block-ryann-apply"],
      skills: ["Python", "Next.js", "TypeScript", "Claude API", "Anthropic SDK", "Git", "GitHub Pages", "Editorial Writing", "Prompt Engineering"],
      defaultBioVariant: "bio-hybrid",
    },
    {
      id: "preset-fellowship",
      label: "Fellowship",
      leadWith: ["exp-1", "exp-3", "exp-4", "exp-2", "block-timeline", "block-patent"],
      skills: ["Python", "Next.js", "TypeScript", "Claude API", "Playwriting", "Editorial Writing", "Prompt Engineering", "Raspberry Pi", "Production Management"],
      defaultBioVariant: "bio-absurd-timeline",
    },
    {
      id: "preset-frontend",
      label: "Frontend / Full-Stack",
      leadWith: ["exp-1", "block-academy", "block-portfolio", "block-ryann-apply"],
      skills: ["Next.js", "React", "TypeScript", "JavaScript", "HTML/CSS", "Tailwind CSS", "Framer Motion", "SEO", "GitHub Pages", "Puppeteer"],
      defaultBioVariant: "bio-tech",
    },
  ],
};
